# this is a more realistic test
# in terms of what the TOML parser
# is for in this case

[package]
name = "My Big Package ;)"
version = "0.0.1"
# authors = [
#     "Felix Angell <mail@felixangell.com>"
# ]

[[array_of_tables]]